language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g grunt-cli
  - npm install grunt
  - npm install grunt-requirejs grunt-contrib-yuidoc grunt-contrib-jshint grunt-contrib-qunit
script: grunt check-server
